version: 10.38.{build}
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - ci
skip_tags: true
skip_branch_with_pr: true
max_jobs: 1
image: Visual Studio 2013
clone_depth: 1
nuget:
  disable_publish_on_pr: true
  disable_publish_octopus: true
before_build:
  - cmd: |
      cd C:\projects\pcre2
      cmake -G"Visual Studio 10 2010" -DPCRE2_SUPPORT_JIT=ON -DPCRE2_BUILD_PCRE2_16=ON -DPCRE2_BUILD_PCRE2_32=ON -DPCRE2_DEBUG=ON -DBUILD_SHARED_LIBS=ON
build_script:
  - cmake --build .
test_script:
  - cmd: |
      msbuild RUN_TESTS.vcxproj
      cd Debug
      pcre2test.exe -C
