name: CI
on: push

jobs:
  linux:
    name: Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          clean: false

      - name: Prepare
        run: ./autogen.sh
        
      - name: Configure
        run: ./configure --enable-jit --enable-pcre2-16 --enable-pcre2-32
        
      - name: Build
        run: make
        
      - name: Test
        run: make check

      - name: Report Failures
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: failed-tests-linux
          path: test*grep

  windows:
    name: 32bit Windows
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure
        run: cmake -DPCRE2_SUPPORT_JIT=ON -DPCRE2_BUILD_PCRE2_16=ON -DPCRE2_BUILD_PCRE2_32=ON -B build -A Win32

      - name: Build
        run: cmake --build build

      - name: Test
        run: |
          cd build\Debug
          mkdir test-output
          ..\..\RunTest.bat

      - name: Report Failures
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: failed-tests
          path: build/debug/test-output/
